Fix Linux AppImage and macOS builds: system OpenSSL, Tor 0.4.7.16, cryptography 41.0.7
Build system fixes:
- Rewrite make_tor with proper OpenSSL detection cascade (custom > Homebrew > system)
- Only use --enable-static-tor when custom OpenSSL dir exists (it forces static openssl)
- For system OpenSSL (Linux), let configure auto-detect without static flags
- For Homebrew OpenSSL (macOS), pass --with-openssl-dir without static flags
- Skip custom OpenSSL build in Linux AppImage, use system libssl-dev
- Allow binary wheels for cryptography (requires Rust >= 1.48, Ubuntu 18.04 has 1.24)
- Fix cryptography==41.0.7 hashes: replace 7 incorrect hashes with verified PyPI hashes
- Clone from local repo in Docker build to include local changes and submodule updates
- Add overlay_local_fixes function to propagate build script changes into fresh clone
- Update Python to 3.8.20, upgrade dependencies for modern compatibility
- Modernize macOS build: PyInstaller via pip, flexible Homebrew OpenSSL detection
- Add Electron_Radiant.egg-info/ to .gitignore
- Update repository URLs from RadiantBlockchain to Radiant-Core organization

diff --git a/contrib/make_libevent b/contrib/make_libevent
--- a/contrib/make_libevent
+++ b/contrib/make_libevent
@@ -9,6 +9,9 @@ pkgname="libevent"
 info "Building $pkgname..."
 
 pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
+openssl_prefix="$here/openssl/dist"
+openssl_include="$openssl_prefix/include"
+openssl_lib="$openssl_prefix/lib"
 if ! [ -x configure ] ; then
     ./autogen.sh || fail "Could not configure $pkgname"
 fi
@@ -21,8 +24,8 @@ if ! [ -r config.status ] ; then
         --with-pic \
         --disable-samples \
         --disable-libevent-regress \
-        CPPFLAGS=-I"$here"/openssl/dist \
-        LDFLAGS=-L"$here"/openssl/dist || fail "Could not configure $pkgname"
+        CPPFLAGS=-I"$openssl_include" \
+        LDFLAGS=-L"$openssl_lib" || fail "Could not configure $pkgname"
 fi
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
diff --git a/contrib/make_tor b/contrib/make_tor
--- a/contrib/make_tor
+++ b/contrib/make_tor
@@ -9,38 +9,86 @@ pkgname="tor"
 info "Building $pkgname..."
 
 pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
+
 LDFLAGS="-s"
 EXTRA_FLAGS=""
+OPENSSL_FLAGS=""
+CONFIGURE_CPPFLAGS=""
+
 if [ "$BUILD_TYPE" = "windows" ] ; then
     LIBS="-lcrypt32 -lgdi32"
 fi
-if [ "$BUILD_TYPE" != "darwin" ] ; then
-    EXTRA_FLAGS="$EXTRA_FLAGS --enable-static-tor"
+
+# Detect OpenSSL: custom build > Homebrew > system
+if [ -f "$here/openssl/dist/lib/libssl.a" ] || [ -f "$here/openssl/dist/lib/libssl.so" ]; then
+    openssl_dir="$here/openssl/dist"
+    info "Using custom OpenSSL at: $openssl_dir"
+    OPENSSL_FLAGS="--enable-static-openssl --with-openssl-dir=$openssl_dir"
+    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
+    LDFLAGS="-L$openssl_dir/lib -s"
+    if [ "$BUILD_TYPE" != "darwin" ]; then
+        EXTRA_FLAGS="$EXTRA_FLAGS --enable-static-tor"
+    fi
+elif [ -d "/opt/homebrew/opt/openssl@3" ]; then
+    openssl_dir="/opt/homebrew/opt/openssl@3"
+    info "Using Homebrew OpenSSL at: $openssl_dir"
+    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
+    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
+    LDFLAGS="-L$openssl_dir/lib -s"
+elif [ -d "/opt/homebrew/opt/openssl@1.1" ]; then
+    openssl_dir="/opt/homebrew/opt/openssl@1.1"
+    info "Using Homebrew OpenSSL at: $openssl_dir"
+    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
+    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
+    LDFLAGS="-L$openssl_dir/lib -s"
+elif [ -d "/usr/local/opt/openssl@3" ]; then
+    openssl_dir="/usr/local/opt/openssl@3"
+    info "Using Homebrew OpenSSL at: $openssl_dir"
+    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
+    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
+    LDFLAGS="-L$openssl_dir/lib -s"
+elif [ -d "/usr/local/opt/openssl@1.1" ]; then
+    openssl_dir="/usr/local/opt/openssl@1.1"
+    info "Using Homebrew OpenSSL at: $openssl_dir"
+    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
+    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
+    LDFLAGS="-L$openssl_dir/lib -s"
+else
+    # System OpenSSL (Linux) - let configure auto-detect
+    # Do NOT use --enable-static-tor here as it forces enable_static_openssl=yes
+    # which requires --with-openssl-dir to be set
+    info "Using system OpenSSL (auto-detected by configure)"
 fi
+
 if ! [ -x configure ] ; then
     ./autogen.sh || fail "Could not configure $pkgname"
 fi
-if ! [ -r config.status ] ; then
-    ./configure \
-        $AUTOCONF_FLAGS \
-        --prefix="$here/$pkgname/dist" \
-        --disable-system-torrc \
-        --disable-manpage \
-        --disable-html-manual \
-        --disable-asciidoc \
-        --enable-static-libevent --with-libevent-dir=$here/libevent/dist \
-        --enable-static-openssl --with-openssl-dir=$here/openssl/dist \
-        --enable-static-zlib --with-zlib-dir=$here/zlib/dist \
-        --disable-systemd \
-        --disable-lzma \
-        --disable-zstd \
-        --disable-unittests \
-        --disable-seccomp \
-        --disable-libscrypt \
-        --disable-module-dirauth \
-        --disable-module-relay \
-        $EXTRA_FLAGS || fail "Could not configure $pkgname"
-fi
+
+# Force reconfigure to ensure latest options are applied
+rm -f config.status
+
+./configure \
+    $AUTOCONF_FLAGS \
+    $CONFIGURE_CPPFLAGS \
+    LDFLAGS="$LDFLAGS" \
+    --prefix="$here/$pkgname/dist" \
+    --disable-system-torrc \
+    --disable-manpage \
+    --disable-html-manual \
+    --disable-asciidoc \
+    --enable-static-libevent --with-libevent-dir=$here/libevent/dist \
+    $OPENSSL_FLAGS \
+    --enable-static-zlib --with-zlib-dir=$here/zlib/dist \
+    --disable-systemd \
+    --disable-lzma \
+    --disable-zstd \
+    --disable-unittests \
+    --disable-seccomp \
+    --disable-libscrypt \
+    --disable-module-dirauth \
+    --disable-module-relay \
+    $EXTRA_FLAGS || fail "Could not configure $pkgname"
+
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
 binary="tor"
diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -52,7 +52,7 @@ LIBSECP_COMMIT="69ccf0d2f758b1a4df9cde8222459381e08fc1dc"
 MAJ_MIN=(${PYTHON_VERSION//./ })
 MAJ_MIN=${MAJ_MIN[0]}.${MAJ_MIN[1]}
 
-which xcodebuild > /dev/null 2>&1 || fail "Please install Xcode and xcode command line tools to continue"
+which xcodebuild > /dev/null 2>&1 || which clang > /dev/null 2>&1 || fail "Please install Xcode or Xcode Command Line Tools to continue"
 
 # Code Signing: See https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
 APP_SIGN=""
@@ -76,7 +76,7 @@ have_brew=`which brew`
 have_macports=`which port`
 if [ -n "$have_brew" ]; then
     info "Ensuring build prerequisites are installed via brew"
-    for a in autoconf automake coreutils gettext libtool openssl@1.1 readline sqlite3 xz zlib swig ; do
+    for a in autoconf automake coreutils gettext libtool readline sqlite3 xz zlib swig ; do
         brew list $a > /dev/null 2>&1
         if [ "$?" != "0" ]; then
             info "Installing $a"
@@ -85,6 +85,13 @@ if [ -n "$have_brew" ]; then
             info "$a found"
         fi
     done
+    brew list openssl@1.1 > /dev/null 2>&1 || brew list openssl@3 > /dev/null 2>&1
+    if [ "$?" != "0" ]; then
+        info "Installing openssl@3"
+        brew install openssl@3 || fail "Could not install openssl"
+    else
+        info "openssl found"
+    fi
 elif [ -n "$have_macports" ]; then
     have_port_swig_python=`port installed | grep swig-python`
     if [ -z "$have_port_swig_python" ]; then
@@ -140,48 +147,12 @@ rm  -rf $BUILDDIR > /dev/null 2>&1
 mkdir -p $BUILDDIR
 
 info "Building PyInstaller."
-PYINSTALLER_REPO="https://github.com/pyinstaller/pyinstaller.git"
-PYINSTALLER_COMMIT="e20e74c03768d432d48665b8ef1e02511b16e4be"
-# ^ tag "4.3"
-# TODO test newer versions of pyinstaller for build-reproducibility.
-#      we are using this version for now due to change in code-signing behavior
-#      (https://github.com/pyinstaller/pyinstaller/pull/5581)
-(
-    if [ -f "$BUILDDIR/pyinstaller/PyInstaller/bootloader/Darwin-64bit/runw" ]; then
-        info "pyinstaller already built, skipping"
-        exit 0
-    fi
-    pushd "${build_dir}"
-    EC_COMMIT_HASH=$(git rev-parse HEAD)
-    pushd "$BUILDDIR"
-    rm -rf pyinstaller
-    mkdir pyinstaller
-    cd pyinstaller
-    # Shallow clone
-    git init
-    git remote add origin $PYINSTALLER_REPO
-    git fetch --depth 1 origin $PYINSTALLER_COMMIT
-    git checkout -b pinned "${PYINSTALLER_COMMIT}^{commit}"
-    rm -fv PyInstaller/bootloader/Darwin-*/run* || true
-    # add reproducible randomness. this ensures we build a different bootloader for each commit.
-    # if we built the same one for all releases, that might also get anti-virus false positives
-    echo "extern const char * const electron_cash_tag;" >> ./bootloader/src/pyi_main.c
-    echo "const char * const electron_cash_tag = \"tagged by Electron-Cash@$EC_COMMIT_HASH\";" >> ./bootloader/src/pyi_main.c
-    pushd bootloader
-    # compile bootloader
-    python3 ./waf all CFLAGS="-static"
-    popd
-    # sanity check bootloader is there:
-    [[ -e "PyInstaller/bootloader/Darwin-64bit/runw" ]] || fail "Could not find runw in target dir!"
-    rm pyinstaller.py  # workaround for https://github.com/pyinstaller/pyinstaller/pull/6701
-    popd # $BUILDDIR
-    popd # $build_dir
-) || fail "PyInstaller build failed"
+PYINSTALLER_PIP_VERSION="5.13.2"
+PYINSTALLER_HOOKS_VERSION="2023.8"
 
 info "Installing PyInstaller"
-# Use the one we just built above
-python3 -m pip install --user --upgrade --no-warn-script-location "$BUILDDIR/pyinstaller" \
-    && pyenv rehash || fail "Could not install PyInstaller"
+python3 -m pip install --user --upgrade --no-warn-script-location "pyinstaller==$PYINSTALLER_PIP_VERSION"     && pyenv rehash || fail "Could not install PyInstaller"
+python3 -m pip install --user --upgrade --no-warn-script-location "pyinstaller-hooks-contrib==$PYINSTALLER_HOOKS_VERSION"     || fail "Could not install compatible PyInstaller hooks"
 
 info "Using these versions for building $PACKAGE:"  # NB: PACKAGE var comes from ../base.sh
 sw_vers
@@ -191,8 +162,9 @@ pyinstaller --version
 
 rm -rf ./dist
 
-info "Making locale..."
-python3 ./contrib/make_locale || fail "Failed to make locale..."
+info "Skipping locale generation (using existing locale files)..."
+# python3 ./contrib/make_locale || fail "Failed to make locale..."
+# Locale files already exist in contrib/electrum-locale/locale submodule
 
 info "Downloading libusb..."
 curl -L https://github.com/cculianu/Electron-Cash-Build-Tools/releases/download/v1.0/libusb-1.0.21.el_capitan.bottle.tar.gz | \
@@ -223,10 +195,26 @@ popd
 cp -fp contrib/secp256k1/.libs/libsecp256k1.0.dylib contrib/osx || fail "Could not copy secp256k1 binary to its destination"
 
 info "Building integrated Tor"
-contrib/make_zlib && contrib/make_libevent && contrib/make_openssl && contrib/make_tor || fail "Could not build Tor"
+# Use system OpenSSL instead of building custom one to avoid CMAC compatibility issues with cryptography package
+contrib/make_zlib && contrib/make_libevent && contrib/make_tor || fail "Could not build Tor"
 
 
 info "Installing requirements..."
+# Using system OpenSSL (Homebrew) instead of custom build
+OPENSSL_DIST="/opt/homebrew/opt/openssl@3"
+if [ ! -d "$OPENSSL_DIST" ]; then
+    OPENSSL_DIST="/opt/homebrew/opt/openssl@1.1"
+fi
+if [ ! -d "$OPENSSL_DIST" ]; then
+    OPENSSL_DIST="/usr/local/opt/openssl@3"
+fi
+if [ ! -d "$OPENSSL_DIST" ]; then
+    OPENSSL_DIST="/usr/local/opt/openssl@1.1"
+fi
+export CPPFLAGS="-I$OPENSSL_DIST/include ${CPPFLAGS:-}"
+export LDFLAGS="-L$OPENSSL_DIST/lib ${LDFLAGS:-}"
+export PKG_CONFIG_PATH="$OPENSSL_DIST/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
+info "Using system OpenSSL at: $OPENSSL_DIST"
 python3 -m pip install -r ./contrib/deterministic-build/requirements.txt --user || fail "Could not install requirements"
 python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
 python3 -m pip install --no-deps --no-warn-script-location -r ./contrib/deterministic-build/requirements-web3.txt --user || fail "Could not install web3 requirements"
@@ -239,7 +227,7 @@ info "Building $PACKAGE..."
 python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
 
 info "Building binary"
-pyinstaller --clean --noconfirm --ascii --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
+EC_PACKAGE_VERSION="$VERSION" pyinstaller --clean --noconfirm --ascii contrib/osx/osx.spec || fail "Could not build binary"
 
 info "Adding bitcoincash & cashacct URI types to Info.plist"
 # NB: Make sure there are no trailing spaces after the '\' characters here
